set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(LLVM_MINGW "/opt/llvm-mingw")
set(TRIPLE "x86_64-w64-mingw32")

set(CMAKE_C_COMPILER   "${LLVM_MINGW}/bin/${TRIPLE}-clang")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW}/bin/${TRIPLE}-clang++")
set(CMAKE_RC_COMPILER  "${LLVM_MINGW}/bin/${TRIPLE}-windres")
set(CMAKE_AR           "${LLVM_MINGW}/bin/llvm-ar")
set(CMAKE_RANLIB       "${LLVM_MINGW}/bin/llvm-ranlib")
set(CMAKE_LINKER       "${LLVM_MINGW}/bin/${TRIPLE}-clang++")

set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW}/${TRIPLE}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
